
// In src/app/layout.js
import '@fontsource/noto-serif'; // npm install @fontsource/noto-serifimport { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
